### ISSUE TITLE
Cannot Add Cover.

### ISSUE THREAD

**Issue by RaBuAc** [slashback100/presence_simulation#151]
I have an entity (Id: cover.rollade_wohnzimmer) which comes from the Homematic IP (RaspberryMatic) which I'm not able to add to the entity list.

I have the following versions:
Presence Simulation Version 4.10.
Core 2024.11.3
Supervisor 2024.11.4
Operating System 13.2
Frontend 20241106.2

I can add the value to the entity list of the PS integration, but when I hit OK, I briefly see a pop up window with the "List of Values must be ..." - which disappears after a second in this  version (that seems to be an issue itself). But anyhow - I cannot add this entity.

![grafik](https://github.com/user-attachments/assets/60294bfa-a1db-4902-9aa8-12ade404006f)

Is there a reason why this value/type of value cannot be added - covers in general are supported as I read.

This value is treid to be added:
![grafik](https://github.com/user-attachments/assets/c0f0af0f-4bc9-44c2-9452-62f304942e4e)

/Rainer

**Comment by Xander-V** [comment]
As far as I know you have to create the group in yaml (configuration.yaml / - group: ) to be able to combine. In the GUI you can only add lights and switches to a light group and cannot create a "general" group. PS should then be able to use them I guess, but I have no cover entities to test this on.

**Comment by RaBuAc** [comment]
@Xander-V 
Many thanks for the reply. Can you give me an example what I have to create in configuration.yaml? I'm not so familiar with groups.
Many thanks,
Rainer

**Comment by Xander-V** [comment]
In configuration.yaml

``` yaml
group:
  ps_group:
    name: "Group for presence simulation"
    icon: mdi:lightbulb-auto-outline
    entities:
      - cover.xyz
      - light.abc
      - light.def
      - switch.ghi
 ```
 
 See ["Old style groups"](https://www.home-assistant.io/integrations/group/#old-style-groups)
