### ISSUE TITLE
Presence simulation triggered after reboot since 2022.6

### ISSUE THREAD

**Issue by lostcontrol** [slashback100/presence_simulation#58]
Since upgrading to HA 2022.6, I had some weird behavior at home with some lights turning on and off magically without human intervention. I tracked it down to HA and especially this extension. Presence simulation is started by the following rule:

```yaml
alias: '[Alarme] Activation de la simulation de présence'
description: ''
trigger:
  - platform: state
    entity_id: switch.alarme_commutation
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 5
      seconds: 0
condition: []
action:
  - service: presence_simulation.start
    data: {}
mode: single
```

I can confirm that `switch.alarme_commutation` is remaining off all the time and that this automation is not triggered when the problem occurs.

Calling `presence_simulation.stop` fixes the issue for me.
