### ISSUE TITLE
Covers

### ISSUE THREAD

**Issue by sciorty** [slashback100/presence_simulation#94]
I start a simulation eith the following service call inside an automation:

```
service: presence_simulation.start
data:
  entity_id:
    - light….
    - cover.serranda_bagno
    - cover.serranda_cameretta
    - cover.serranda_soggiorno
  delta: 7
  restore_states: false
  random: 300
```

But i noticed that the covers are not fully closed/opened like they were in the 7 days before, but rather set on a certain randome percentage.

Is that normal?
