### ISSUE TITLE
presence simulation does not work

### ISSUE THREAD

**Issue by stefancvetkovic** [slashback100/presence_simulation#97]
Hello, 

I added your integration but when I hit run service, nothing happens like in minutes (10 minutes)
I was yesterday at home, and I know that some lights were turned on, but now it wont tun it on?
```
service: presence_simulation.start
data:
  entity_id:
    - light.all_lights
  delta: 20
  restore_states: true
  random: 50
```
I dont know should I use for delta just 1 like one day before? or?
I restarted HA.
